site_name: My MkDocs Material Documentation
site_url: https://example.com/
theme:
    name: material
    font:
        text: Merriweather Sans
        code: Red Hat Mono
    icon:
        logo: material/cards
    # favicon: path/to/favicon.ico
    features:
        - navigation.footer
    palette:
        # Dark Mode
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Dark mode
          primary: light blue
          accent: deep purple

        # Light Mode
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Light mode
          primary: blue
          accent: deep orange

    # logo:
    #   icon: home
    #   text: My Docs
    # favicon: path/to/favicon.ico
    # search: true

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true

extra:
    social:
        - icon: simple/youtube
          link: https://youtube.com/@pastranadigital
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/omar-pastrana/

copyright: Copyright &copy; 2024 Omar Pastrana
