site_name: Spotify for Developers (MkDocs Clone)
site_url: https://example.com/
theme:
    name: material
    font:
        text: Merriweather Sans
        code: Red Hat Mono
    logo: /assets/logo.png
    favicon: /assets/favicon.ico
    features:
        - navigation.path
        - navigation.top
        # - toc.integrate
        - navigation.footer
        - navigation.expand
    palette:
        # Dark Mode
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Dark mode
          primary: deep purple
          accent: teal

        # Light Mode
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Light mode
          primary: deep purple
          accent: teal

plugins:
    - search
    - awesome-pages # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true

extra:
    social:
        - icon: simple/youtube
          link: https://youtube.com/@pastranadigital
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/omar-pastrana/

extra_css:
    - stylesheets/extra.css

copyright: Copyright &copy; 2025 Spotify AB
